#Instead of using TAB for indentation, use two spaces at the place of one TAB

#Controller to control robot arm joints
hip_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: [hip1, hip2, hip3, hip4]

#Controller to control end effector joints
leg_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: [leg1, leg2, leg3, leg4]

#Controller to continuously publish joint states/positions
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50
